### ISSUE TITLE
plugin crashes trying to create dupe entry in jar

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.swarm#3]
Should just filter out dupes.

```
/Users/gavin/ceylon/dist/dist/bin/ceylon swarm --provided-module javax:org.wildfly.swarm:jaxrs jaxrs.example/1.0.0
ceylon swarm: duplicate entry: WEB-INF/lib/org.wildfly.swarm.datasources-2016.9.
jar
java.util.zip.ZipException: duplicate entry: WEB-INF/lib/org.wildfly.swarm.datasources-2016.9.jar
    at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
    at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
    at com.redhat.ceylon.tools.war.CeylonWarTool$EntrySpec.write(CeylonWarTool.java:349)
    at com.redhat.ceylon.tools.war.CeylonWarTool.writeJarFile(CeylonWarTool.java:332)
    at com.redhat.ceylon.tools.war.CeylonWarTool.run(CeylonWarTool.java:202)
    at ceylon.swarm.CeylonSwarmTool.run(CeylonSwarmTool.ceylon:35)
    at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:524)
    at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:405)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:115)
    at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
    at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.redhat.ceylon.launcher.Bootstrap.runInternal(Bootstrap.java:139)
    at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:93)
    at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:85)

Process finished with exit code 2
```

**Comment by FroMage** [comment]
Do you remember what you module imports looked like?

**Comment by FroMage** [comment]
I can't reproduce with your `javax:org.wildfly.swarm:jaxrs` module, because it's just wrong. But I can't also reproduce with `import maven:"org.wildfly.swarm:jaxrs" "2016.9"` because that only works with `--fully-export-maven-dependencies` and the jarless poms support in 1.3.1, and I'm sure you tested with 1.3.0.

**Comment by FroMage** [comment]
Also I'm pretty sure we can't have duplicate modules in there, so unless there are _two_ modules that ended up having the same `jar` (with the same version), I don't understand how this can happen.
